# Generated by Django 5.1.4 on 2024-12-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_label_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='tasks',
        ),
    ]
